# Checks to weekly monitor the status of the main branch.
name: Weekly checks

on:
  schedule:
    # Run every monday on 9:00 in the morning (UTC).
    - cron: "0 9 * * 1"
  # Make it possible to trigger the checks manually.
  workflow_dispatch:

jobs:

  analyze:
    uses: ./.github/workflows/codeql-analysis.yml
